### ISSUE TITLE
Hosting through GitHub?

### ISSUE THREAD

**Issue by ShannaSeigel** [binyamin/eleventy-garden#31]
Hi fellow Maryland person!

I saw your link from Obsidian and was checking out your project. I have pretty limited development experience (if development is even the right word here) and haven't worked with websites in a looooong time. You mentioned hosting on Netlify or elsewhere in "Getting Started." Could the site just be hosted from a GitHub repo of notes?

**Comment by binyamin** [comment]
👋 Hello!

> Could the site just be hosted from a GitHub repo of notes?

I'm not sure what you meant to ask, so here are a couple possible answers 😜.
- Could you host the website with [GitHub Pages](https://pages.github.com)?\
Yes, but I find Netlify much easier.
- Could you store the notes on GitHub instead of Netlify?\
You _can't_ store the notes on Netlify. You would store the notes on GitHub, and Netlify would use the GitHub repository to host the website.
- Could you store the notes and the site as separate repositories?\
Yes. I do that with my own site [here](https://github.com/binyamin/binyam.in/blob/master/scripts/fetchNotes.js). It takes some extra playing around, though.

Let me know if you meant something entirely different, or if I didn't explain something well.

**Comment by binyamin** [comment]
resolved on discord
